Class {
	#name : 'Spieler',
	#superclass : 'Object',
	#instVars : [
		'firstName',
		'lastName',
		'email'
	],
	#category : 'TurnierplanerApp'
}

{ #category : 'Not categorized' }
Spieler >> email [

	^email
]

{ #category : 'Not categorized' }
Spieler >> email: anEmail [

	email := anEmail
]

{ #category : 'Not categorized' }
Spieler >> firstName [
	
	^firstName
]

{ #category : 'Not categorized' }
Spieler >> firstName: aFirstName [

	firstName := aFirstName
]

{ #category : 'Not categorized' }
Spieler >> lastName [

	^lastName
]

{ #category : 'Not categorized' }
Spieler >> lastName: aLastName [

	lastName := aLastName
]
