Class {
	#name : 'TournamentType',
	#superclass : 'Object',
	#category : 'TurnierplanerApp'
}

{ #category : 'Event' }
TournamentType >> getCollectionOfGamesWithPlayers: aCollectionOfPlayers [

	 ^self error: 'Method not implemented'
]

{ #category : 'Event' }
TournamentType >> getCollectionOfGamesWithTeams: aCollectionOfTeams [

	 ^self error: 'Method not implemented'
]

{ #category : 'Event' }
TournamentType >> getNumberOfLaps: aNumber [

 ^self error: 'Method not implemented'
]
