Class {
	#name : 'Wette',
	#superclass : 'Object',
	#instVars : [
		'spieler',
		'schaetzung'
	],
	#category : 'TurnierplanerApp'
}

{ #category : 'Not categorized' }
Wette >> schaetzung [

	^schaetzung
]

{ #category : 'Not categorized' }
Wette >> schaetzung: anObject [

	schaetzung := anObject
]

{ #category : 'Not categorized' }
Wette >> spieler [

	^spieler
]

{ #category : 'Not categorized' }
Wette >> spieler: anObject [

	spieler := anObject
]

{ #category : 'Not categorized' }
Wette >> TonelLoaderSubApplication [

]
